# Generated by Django 6.0.7 on 2026-07-14 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_ID', models.CharField(max_length=32, verbose_name='留言ID')),
                ('board_user', models.CharField(max_length=255, verbose_name='留言用户')),
                ('board_message', models.TextField(verbose_name='留言内容')),
                ('board_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言板',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_ID', models.CharField(max_length=32, verbose_name='评论ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('comment_user', models.CharField(max_length=255, verbose_name='评论用户')),
                ('movie', models.CharField(max_length=32, verbose_name='影片名')),
                ('discussion', models.CharField(max_length=256, verbose_name='评论内容')),
                ('comment_score', models.FloatField(verbose_name='评分')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='电影标题')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='导演')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('poster', models.CharField(blank=True, default='assets/movie_posters/default.jpg', max_length=255, verbose_name='海报路径')),
                ('actors', models.CharField(blank=True, max_length=255, null=True, verbose_name='演员表')),
                ('regions', models.CharField(blank=True, max_length=255, null=True, verbose_name='地区')),
                ('types', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影集',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_ID', models.CharField(max_length=32, verbose_name='用户ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(default='', max_length=255, verbose_name='用户昵称')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('registration', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('groups', models.ManyToManyField(blank=True, related_name='userinfo_groups', related_query_name='userinfo', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='userinfo_permissions', related_query_name='userinfo', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_user', models.CharField(max_length=255, verbose_name='收藏用户名')),
                ('collect_movie', models.CharField(max_length=32, verbose_name='影片名')),
                ('movie_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='CfRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='推荐度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cfrecs', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cfrecs', to='myapp.movie')),
            ],
            options={
                'verbose_name': '协同过滤推荐',
                'verbose_name_plural': '协同过滤推荐集',
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='评分')),
                ('rating_time', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='myapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户评分',
                'verbose_name_plural': '用户评分集',
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
