# Generated by Django 6.0.1 on 2026-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='电影标题')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('data', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('poster', models.URLField(blank=True, max_length=255, null=True, verbose_name='海报链接')),
                ('actors', models.CharField(blank=True, max_length=255, null=True, verbose_name='演员表')),
                ('regions', models.CharField(blank=True, max_length=255, null=True, verbose_name='地区')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影集',
            },
        ),
    ]
