# Generated by Django 6.0.1 on 2026-01-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='type',
            new_name='types',
        ),
    ]
