# Generated by Django 6.0.1 on 2026-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0002_rename_data_movie_date_rename_type_movie_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_ID', models.CharField(max_length=32, verbose_name='用户ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('sex', models.IntegerField(choices=[(2, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('registration', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('groups', models.ManyToManyField(blank=True, related_name='userinfo_groups', related_query_name='userinfo', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='userinfo_permissions', related_query_name='userinfo', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
