# Generated by Django 6.0.1 on 2026-01-18 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_movie_poster_alter_userinfo_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_ID', models.CharField(max_length=32, verbose_name='评论ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('comment_user', models.CharField(max_length=255, verbose_name='评论用户')),
                ('movie', models.CharField(max_length=32, verbose_name='影片名')),
                ('discussion', models.CharField(max_length=256, verbose_name='评论内容')),
                ('comment_score', models.FloatField(verbose_name='评分')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, default='assets/movie_posters/default.jpg', max_length=255, verbose_name='海报路径'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='', max_length=255, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(2, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_user', models.CharField(max_length=255, verbose_name='收藏用户名')),
                ('collect_movie', models.CharField(max_length=32, verbose_name='影片名')),
                ('movie_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
            ],
        ),
    ]
