# Generated by Django 6.0.1 on 2026-01-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comment_alter_movie_poster_alter_userinfo_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='收藏用户id')),
                ('movie_id', models.IntegerField(verbose_name='影片id')),
                ('rating', models.FloatField(verbose_name='推荐度')),
            ],
        ),
    ]
