# Generated by Django 6.0.1 on 2026-01-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_ID', models.CharField(max_length=32, verbose_name='留言ID')),
                ('board_user', models.CharField(max_length=255, verbose_name='留言用户')),
                ('board_message', models.TextField(verbose_name='留言内容')),
                ('board_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言板',
            },
        ),
    ]
