# Generated by Django 6.0.1 on 2026-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='留言时间'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_user',
            field=models.CharField(db_index=True, max_length=255, verbose_name='留言用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.CharField(db_index=True, max_length=255, verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.CharField(db_index=True, max_length=32, verbose_name='影片名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='regions',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='电影标题'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='movie_id',
            field=models.IntegerField(db_index=True, verbose_name='影片id'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='user_id',
            field=models.IntegerField(db_index=True, verbose_name='收藏用户id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['board_user', 'board_time'], name='myapp_board_board_u_2bf7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['comment_user', 'comment_time'], name='myapp_comme_comment_0d77ca_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['movie', 'comment_time'], name='myapp_comme_movie_241003_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'score'], name='myapp_movie_title_83bd57_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['types', 'score'], name='myapp_movie_types_c5a222_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['date', 'score'], name='myapp_movie_date_32f9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='rec',
            index=models.Index(fields=['user_id', 'rating'], name='myapp_rec_user_id_f05967_idx'),
        ),
        migrations.AddIndex(
            model_name='rec',
            index=models.Index(fields=['movie_id', 'rating'], name='myapp_rec_movie_i_b32177_idx'),
        ),
    ]
