# Generated by Django 6.0.1 on 2026-02-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_board_board_time_alter_board_board_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='推荐度')),
            ],
            options={
                'verbose_name': '协同过滤推荐',
                'verbose_name_plural': '协同过滤推荐记录',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='评分')),
                ('rating_time', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分记录',
            },
        ),
        migrations.AlterModelOptions(
            name='rec',
            options={'verbose_name': '推荐', 'verbose_name_plural': '推荐记录'},
        ),
        migrations.RemoveIndex(
            model_name='board',
            name='myapp_board_board_u_2bf7b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='myapp_comme_comment_0d77ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='myapp_comme_movie_241003_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='myapp_movie_title_83bd57_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='myapp_movie_types_c5a222_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='myapp_movie_date_32f9bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='rec',
            name='myapp_rec_user_id_f05967_idx',
        ),
        migrations.RemoveIndex(
            model_name='rec',
            name='myapp_rec_movie_i_b32177_idx',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='留言时间'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_user',
            field=models.CharField(max_length=255, verbose_name='留言用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.CharField(max_length=255, verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.CharField(max_length=32, verbose_name='影片名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='regions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='电影标题'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='movie_id',
            field=models.IntegerField(verbose_name='影片id'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='user_id',
            field=models.IntegerField(verbose_name='收藏用户id'),
        ),
        migrations.AddField(
            model_name='cfrec',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cf_recs', to='myapp.movie', verbose_name='电影'),
        ),
        migrations.AddField(
            model_name='cfrec',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cf_recs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='电影'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
    ]
