# Generated by Django 6.0.1 on 2026-02-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cfrec_rating_alter_rec_options_and_more'),
        ('myapp', '0009_rating_alter_rec_options_and_more'),
    ]

    operations = [
    ]
