# Generated by Django 6.0.1 on 2026-04-08 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_merge_20260201_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfrec',
            options={'verbose_name': '协同过滤推荐', 'verbose_name_plural': '协同过滤推荐集'},
        ),
        migrations.AlterModelOptions(
            name='collect',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏集'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论集'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': '用户评分', 'verbose_name_plural': '用户评分集'},
        ),
        migrations.RemoveField(
            model_name='board',
            name='board_user',
        ),
        migrations.AlterUniqueTogether(
            name='collect',
            unique_together={('user', 'movie')},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_user',
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_boards', to=settings.AUTH_USER_MODEL, verbose_name='留言用户'),
        ),
        migrations.AddField(
            model_name='collect',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_collects', to='myapp.movie', verbose_name='收藏电影'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collects', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='cfrec',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cfrecs', to='myapp.movie'),
        ),
        migrations.AlterField(
            model_name='cfrec',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cfrecs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_comments', to='myapp.movie', verbose_name='评论电影'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='myapp.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cfrec',
            unique_together={('user', 'movie')},
        ),
        migrations.DeleteModel(
            name='Rec',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='collect_movie',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='collect_user',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='movie_information',
        ),
    ]
